import { environment } from '../environments/environment';

export class AppSettings {
  public static API = {
    AUTH: environment.apiUrl + 'validUser',
    forgot_password: environment.apiUrl + 'forget_password',
    add_company: environment.apiUrl + 'company',
    customer: environment.apiUrl + 'customer',
    change_password: environment.apiUrl + 'change_password',
    emp_details: environment.apiUrl + 'emp_details',
    employee_add: environment.apiUrl + 'employee',
    project: environment.apiUrl + 'project',
    department: environment.apiUrl + 'department',
    designation: environment.apiUrl + 'designations',
    roles: environment.apiUrl + 'roles',
    country: environment.apiUrl + 'country',
    state: environment.apiUrl + 'state',
    project_group: environment.apiUrl + 'project_group',
    project_emp_linking: environment.apiUrl + 'project_emp_linking',
    getProjectEmployeesByID: environment.apiUrl + 'getProjectEmployeesByID',
    addTicket: environment.apiUrl + 'addTicket',
    getEmpProjectsList: environment.apiUrl + 'getEmpProjectsList',
    ticketList: environment.apiUrl + 'ticketList',
    ticket_history: environment.apiUrl + 'ticket_history',
    getPMProjectsList: environment.apiUrl + 'getPMProjectsList',
    adminGetCountDashboard: environment.apiUrl + 'adminDashboardCount',
    getTicketHistory: environment.apiUrl + 'getTicketHistory',
    pmDashboardCount: environment.apiUrl + 'pmDashboardCount',
    userDashboardCount: environment.apiUrl + 'userDashboardCount',
    clientDashboardCount : environment.apiUrl + 'clientDashboardCount',
    category : environment.apiUrl + 'category',
    timeSheet : environment.apiUrl + 'timeSheet',
    projectReport: environment.apiUrl + 'employeeProjectTicketData',
    timesheetReport: environment.apiUrl + 'employeeProjectTimeSheet',
    adminProjectReport: environment.apiUrl + 'adminProjectReport',
    adminEmployeeReport : environment.apiUrl + 'adminEmployeeReport',
    adminTicketDetailsReport: environment.apiUrl + 'adminTicketDetailsReport',
    adminTimeSheetReport:environment.apiUrl + 'adminTimeSheetReport',
    employeeAdminReport:environment.apiUrl + 'employeeAdminReport',
    edit_profile:environment.apiUrl + 'edit_profile',
    summaryReport:environment.apiUrl + 'summaryReport',
    others: environment.apiUrl + 'others',
    getempReport: environment.apiUrl + 'monthlyReportEmp',
  };
}
